# Generated by Django 5.0.1 on 2024-02-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNumber', models.CharField(max_length=6, verbose_name='Гос. номер авто')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=30, verbose_name='Имя клиента')),
                ('clientSurname', models.CharField(max_length=30, verbose_name='Фамилия клиента')),
                ('phoneNumber', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=30, verbose_name='Имя водителя')),
                ('driverSurname', models.CharField(max_length=30, verbose_name='Фамилия водителя')),
            ],
        ),
        migrations.CreateModel(
            name='Medics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicName', models.CharField(max_length=30, verbose_name='Имя врача')),
                ('medicSurame', models.CharField(max_length=30, verbose_name='Фамилия врача')),
                ('medic_position', models.CharField(max_length=15, verbose_name='Должность врача')),
                ('is_working', models.BooleanField(default=False, verbose_name='На смене')),
            ],
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, verbose_name='Адрес вызова')),
                ('diagnose', models.CharField(max_length=40, verbose_name='Предварительный диагноз при вызове')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления вызова')),
                ('time_accepted', models.DateTimeField(auto_now=True, verbose_name='Время принятия вызова')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_arrived', models.BooleanField(default=False)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.cars', verbose_name='id кареты')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_ids', to='main_app.clients', verbose_name='id клиента')),
                ('client_phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_phones', to='main_app.clients', to_field='phoneNumber')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='car_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.drivers'),
        ),
    ]
