# Generated by Django 5.0.1 on 2024-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес вызова'),
        ),
    ]
