# Generated by Django 5.0.1 on 2024-02-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_medics_car_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calls',
            options={'verbose_name': 'Таблица вызовов', 'verbose_name_plural': 'Таблица вызовов'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Зарегистрированные кареты', 'verbose_name_plural': 'Зарегистрированные кареты'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='drivers',
            options={'verbose_name': 'Водители карет', 'verbose_name_plural': 'Водители карет'},
        ),
        migrations.AlterModelOptions(
            name='medics',
            options={'verbose_name': 'Мед.работники', 'verbose_name_plural': 'Мед.работники'},
        ),
        migrations.RenameField(
            model_name='medics',
            old_name='medicSurame',
            new_name='medicSurname',
        ),
    ]
