# Generated by Django 5.0.1 on 2024-02-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_calls_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.cars', verbose_name='id машины')),
            ],
        ),
    ]
