# Generated by Django 5.0.1 on 2024-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_carsposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
