# Generated by Django 5.0.1 on 2024-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_calls_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='is_working',
        ),
        migrations.AddField(
            model_name='cars',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
