# Generated by Django 5.0.1 on 2024-02-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_cars_is_working_cars_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='is_free',
        ),
        migrations.AddField(
            model_name='cars',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
