# Generated by Django 5.0.1 on 2024-02-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_cars_is_free_cars_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='category',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calls',
            name='time_accepted',
            field=models.DateTimeField(null=True, verbose_name='Время принятия вызова'),
        ),
        migrations.AlterField(
            model_name='calls',
            name='time_arrived',
            field=models.DateTimeField(null=True, verbose_name='Время прибытия на вызов'),
        ),
    ]
