# Generated by Django 5.0.1 on 2024-02-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_calls_client_id_calls_client_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.AddField(
            model_name='carsposition',
            name='call_address',
            field=models.CharField(default='None'),
        ),
        migrations.DeleteModel(
            name='Medics',
        ),
    ]
