# Generated by Django 5.0.1 on 2024-02-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_calls_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsposition',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
