# Generated by Django 5.0.1 on 2024-02-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_carsposition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='diagnose',
            field=models.CharField(max_length=100, verbose_name='Предварительный диагноз при вызове'),
        ),
    ]
